src/web/ExpoGAN.Web/Pages/Emojis.cshtml.cs
using ExpoGAN.Web.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace ExpoGAN.Web.Pages
{
    //https://rvera.github.io/image-picker/
    public class EmojisModel : PageModel
    {
        public const int DefaultMaxColors = 3;

        private readonly ILogger<PageModel> _logger;
        private readonly IHostEnvironment _environment;
        private readonly EmojisService _emojisService;

        public string EmojisServiceGuid
        { 
            get => HttpContext.Session.GetString(nameof(EmojisServiceGuid)); 
            set => HttpContext.Session.SetString(nameof(EmojisServiceGuid), value);
        }
        public bool EmojisExist
        {
            get => HttpContext.Session.GetBoolean(nameof(EmojisExist)) == true;
            set => HttpContext.Session.SetBoolean(nameof(EmojisExist), value);
        }
        public string FirstEmojiId
        {
            get => HttpContext.Session.GetString(nameof(FirstEmojiId));
            set => HttpContext.Session.SetString(nameof(FirstEmojiId), value);
        }
        public string SecondEmojiId
        {
            get => HttpContext.Session.GetString(nameof(SecondEmojiId));
            set => HttpContext.Session.SetString(nameof(SecondEmojiId), value);
        }
        public bool InterpolationExists
        {
            get => HttpContext.Session.GetBoolean(nameof(InterpolationExists)) == true;
            set => HttpContext.Session.SetBoolean(nameof(InterpolationExists), value);
        }

        public bool GenerateEmojisError { get; set; }
        public bool PickEmojisError { get; set; }
        public bool InterpolateEmojisError { get; set; }
        public string Message { get; set; }

        [BindProperty]
        public int[] SelectedEmojis { get; set; }

        public EmojisModel(ILogger<PageModel> logger, IHostEnvironment environment, EmojisService emojisService)
        {
            _logger = logger;
            _environment = environment;
            _emojisService = emojisService;
        }

        public async Task OnGetAsync()
        {
            if (string.IsNullOrEmpty(EmojisServiceGuid))
            {
                EmojisServiceGuid = Guid.NewGuid().ToString();
            }
        }

        public async Task<IActionResult> OnPostGenerateAsync()
        {
            EmojisExist = false;
            FirstEmojiId = string.Empty;
            SecondEmojiId = string.Empty;
            InterpolationExists = false;

            try
            {
                var location = await _emojisService.GenerateEmojisAsync(EmojisServiceGuid);
                Console.WriteLine(location);
                EmojisExist = true;
                return Page();
            }
            catch (HttpRequestException ex)
            {
                GenerateEmojisError = true;
                Message = ex.Message;
            }

            return Page();
        }

        public async Task<IActionResult> OnPostPickAsync()
        {
            if (SelectedEmojis.Length < 2)
            {
                PickEmojisError = true;
                Message = "You must select 2 emojis before proceeding!";
                return Page();
            }

            FirstEmojiId = SelectedEmojis[0].ToString();
            SecondEmojiId = SelectedEmojis[1].ToString();

            try
            {
                var location = await _emojisService.InterpolateEmojisAsync(EmojisServiceGuid, FirstEmojiId, SecondEmojiId);
                Console.WriteLine(location);
                InterpolationExists = true;
                return Page();
            }
            catch (HttpRequestException ex)
            {
                InterpolateEmojisError = true;
                Message = ex.Message;
            }

            return Page();
        }
    }
}

src/web/ExpoGAN.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExpoGAN.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/web/ExpoGAN.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ExpoGAN.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public bool HasArtPieceErrors { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public async Task OnGetAsync()
        {
            try
            {
            }
            catch (Exception)
            {
                HasArtPieceErrors = true;
            }
        }
    }
}

src/web/ExpoGAN.Web/Pages/Simpsonify.cshtml.cs
using ExpoGAN.Web.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Threading.Tasks;

namespace ExpoGAN.Web.Pages
{
    public class SimpsonifyModel : PageModel
    {
        public const int DefaultMaxColors = 3;

        private readonly ILogger<PageModel> _logger;
        private readonly IHostEnvironment _environment;
        private readonly EmojisService _emojisService;

        public bool GetMessageError { get; set; }
        public string Message { get; set; }

        public bool PostImageUrlError { get; set; }

        [BindProperty]
        public string ImageUrl { get; set; }

        [BindProperty]
        public int? MaxColors { get; set; } = DefaultMaxColors;

        [BindProperty]
        public IFormFile UploadedFile { get; set; }

        public SimpsonifyModel(ILogger<PageModel> logger, IHostEnvironment environment, EmojisService emojisService)
        {
            _logger = logger;
            _environment = environment;
            _emojisService = emojisService;
        }

        public async Task OnGetAsync()
        {
            try
            {
                //Message = await _recolorService.GetMessageAsync();
            }
            catch(HttpRequestException)
            {
                GetMessageError = true;
                Message = string.Empty;
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            //try
            //{
            //    if (!string.IsNullOrEmpty(ImageUrl))
            //    {
            //        var location = await _recolorService.SendImageUrlAsync(
            //            new Uri(ImageUrl),
            //            MaxColors.Value
            //        );
            //        Message = location?.ToString();
            //        Response.Redirect("http://localhost:5000" + location.PathAndQuery);
            //        var queryString = HttpUtility.ParseQueryString(location.Query);
            //        var filename = queryString["filename"];
            //        var guidPart = filename.Substring(0, 36);

            //        var piece = new ArtPiece(Guid.Parse(guidPart), filename, DateTime.Now);
            //        await _artPieceRepository.CreateAsync(piece);

            //        return RedirectToPage("/ArtPieces/Details", new { id = piece.Id });
            //    }
            //    else
            //    {
            //        if (UploadedFile == null || UploadedFile.Length == 0)
            //        {
            //            return BadRequest();
            //        }

            //        using var fileStream = UploadedFile.OpenReadStream();
            //        byte[] bytes = new byte[UploadedFile.Length];
            //        await fileStream.ReadAsync(bytes.AsMemory(0, (int)UploadedFile.Length));

            //        var piece = new ArtPiece(UploadedFile.FileName);

            //        var location = await _recolorService.SendImageFileAsync(
            //            piece.Filename,
            //            bytes,
            //            MaxColors.Value
            //        );

            //        await _artPieceRepository.CreateAsync(piece);

            //        Message = location?.ToString();

            //        return RedirectToPage("/ArtPieces/Details", new { id = piece.Id });
            //    }
            //}
            //catch (HttpRequestException ex)
            //{
            //    PostImageUrlError = true;
            //    Message = ex.Message;
            //}

            return StatusCode(200);
        }
    }
}

src/web/ExpoGAN.Web/Pages/Emojis.cshtml
@page
@model ExpoGAN.Web.Pages.EmojisModel
@{
    ViewData["Title"] = "Emojis Generator with DCGAN";
}

@section CSS
{
    <link rel="stylesheet" href="@Url.Content("/css/image-picker.css")" />
}

@section Scripts
{
    <script type="text/javascript" src="@Url.Content("/js/image-picker.min.js")"></script>

    <script type="text/javascript">
        $("select.image-picker").imagepicker({ limit: 2 });
            //jQuery("select.image-picker").imagepicker({
            //    hide_select: false,
            //});
    </script>
}

<div class="text-center">
    <h1 class="display-3">@ViewData["Title"]</h1>
</div>

<div class="container">
    @if (Model.GenerateEmojisError)
    {
        <div class="row mb-4">
            <div class="col-md-12">
                <p>
                    @Model.Message
                </p>
            </div>
        </div>
    }

    <ul class="nav nav-tabs" id="tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="demo-tab" data-toggle="tab" href="#demo" role="tab" aria-controls="demo" aria-selected="true">Demo</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="model-tab" data-toggle="tab" href="#model" role="tab" aria-controls="model" aria-selected="false">AI Model</a>
        </li>
    </ul>
    <div class="tab-content" id="tabsContent">
        <div class="tab-pane fade show active" id="demo" role="tabpanel" aria-labelledby="demo-tab">
            <div class="row mb-4">
                <div class="col-md-12">
                    <h2 class="display-5">Instructions:</h2>
                    <ol>
                        <li>Click on 'Generate' to view 45 newly generated emojis.</li>
                        <li>Pick 2 emojis from the list by clicking on them.</li>
                        <li>Click the 'Pick Selected Emojis' button.</li>
                        <li>Use the slider to morph from one emoji to the other.</li>
                    </ol>

                    <form asp-page-handler="generate" method="post" class="mb-3">
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Generate Emojis</button>
                        </div>
                    </form>
                </div>
            </div>
            @if (Model.EmojisExist)
            {
                <hr />
                <div class="row mb-4">
                    <div class="col-md-12">
                        <form asp-page-handler="pick" method="post" class="mb-3">
                            <select asp-for="SelectedEmojis" class="image-picker show-html" data-limit="2" multiple="multiple">
                                @for (int i = 0; i < 53; i++)
                                {
                                    <option data-img-src="@Url.Content($"/data/emojis/{Model.EmojisServiceGuid}/{i}.png")" value="@(i)">Emoji #@(i)</option>
                                }
                            </select>

                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Pick Selected Emojis</button>
                            </div>
                        </form>
                    </div>
                </div>
            }
            @if (!string.IsNullOrEmpty(Model.FirstEmojiId))
            {
                <hr />
                <div class="row mb-4">
                    <div class="col-md-1">
                        <div class="text-center">
                            <img src="@Url.Content($"/data/emojis/{Model.EmojisServiceGuid}/{Model.FirstEmojiId}.png")" />
                        </div>
                    </div>
                    <div class="col-md-10 text-center">
                        <div class="text-center">
                            <img src="@Url.Content($"/data/emojis/{Model.EmojisServiceGuid}/morphs/morphs.png")" />
                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="text-center">
                            <img src="@Url.Content($"/data/emojis/{Model.EmojisServiceGuid}/{Model.SecondEmojiId}.png")" />
                        </div>
                    </div>
                </div>
            }
            <div class="tab-pane fade" id="model" role="tabpanel" aria-labelledby="model-tab">
            </div>
        </div>
    </div>
</div>

src/web/ExpoGAN.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "ExpoGAN";
}

<div class="text-center">
    <h1 class="display-3">ExpoGAN</h1>
    <h2 class="display-5">Explore GAN models with these interactive demos!</h2>
</div>
<hr class="mt-3 mb-3" />
<div class="container">
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card mb-3 text-center align-items-center">
                <img class="card-img-top" src="~/images/emojis-generator-banner.png" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">
                        Interpolating between generated emojis with DCGAN
                    </h5>
                    <p class="card-text">An interactive emoji generator that allows you to pick 2 randomly generated emojis and visualize the interpolation from one to the other.</p>
                    <a class="btn btn-primary" asp-area="" asp-page="/Emojis">Generate Emojis!</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card mb-3 text-center align-items-center">
                <img class="card-img-top" src="~/images/emojis-latentship-banner.png" alt="Card image cap" style="width: 20%;">
                <div class="card-body">
                    <h5 class="card-title">
                        Generating emojis from latent space manipulations with DCGAN
                    </h5>
                    <p class="card-text">An interactive emoji generator that allows you draw (manipulate) the latent space and visualize its emoji representation.</p>
                    <a class="btn btn-primary" href="http://localhost:8000/">Generate Emojis!</a>
                </div>
            </div>
        </div>
    </div>
</div>

src/web/ExpoGAN.Web/Pages/Simpsonify.cshtml
@page
@model ExpoGAN.Web.Pages.SimpsonifyModel
@{
    ViewData["Title"] = "Simpsonify with CycleGAN";
}

<div class="text-center">
    <h1 class="display-3">@ViewData["Title"]</h1>
</div>

<div class="container">
    @if (Model.GetMessageError)
    {
        <div class="row mb-4">
            <div class="col-md-12">
                <p>
                    @Model.Message
                </p>
            </div>
        </div>
    }

    <ul class="nav nav-tabs" id="recolorTabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="fromUrl-tab" data-toggle="tab" href="#fromUrl" role="tab" aria-controls="fromUrl" aria-selected="true">From URL</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="fromFile-tab" data-toggle="tab" href="#fromFile" role="tab" aria-controls="fromFile" aria-selected="false">From File</a>
        </li>
    </ul>
    <div class="tab-content" id="recolorTabsContent">
        <div class="tab-pane fade show active" id="fromUrl" role="tabpanel" aria-labelledby="fromUrl-tab">
            <div class="row mb-4">
                <div class="col-md-12">
                    <form method="post">
                        <div class="form-group">
                            <label for="ImageUrl">Image URL:</label>
                            <input type="url" class="form-control" asp-for="ImageUrl" aria-describedby="ImageUrlHelp" placeholder="Enter Image URL">
                            <small id="ImageUrlHelp" class="form-text text-muted text-center">Example: <a href="https://c0.lestechnophiles.com/www.numerama.com/wp-content/uploads/2019/01/meme.jpg">https://c0.lestechnophiles.com/www.numerama.com/wp-content/uploads/2019/01/meme.jpg</a></small>
                        </div>
                        <div class="form-group">
                            <label for="MaxColors">Number of colors to use:</label>
                            <input type="number" class="form-control" asp-for="MaxColors" placeholder="3">
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="fromFile" role="tabpanel" aria-labelledby="fromFile-tab">
            <div class="row mb-4">
                <div class="col-md-12">
                    <form method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <input type="file" asp-for="UploadedFile" />
                        </div>
                        <div class="form-group">
                            <label for="MaxColors">Number of colors to use:</label>
                            <input type="number" class="form-control" asp-for="MaxColors" placeholder="3">
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>